
# H2 in-memory DB (ephemeral)
spring.datasource.url=jdbc:h2:file:../data/accountsdb;DB_CLOSE_ON_EXIT=FALSE;MODE=PostgreSQL
spring.datasource.username=sa
spring.datasource.password=

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

# H2 console
spring.h2.console.enabled=true

# i18n
spring.messages.basename=messages
spring.mvc.locale-resolver=accept-header
# spring.mvc.locale=tr_TR  # uncomment to default to Turkish
server.port=8082

spring.mvc.cors.mappings.[/**].allowed-origins=*
spring.mvc.cors.mappings.[/**].allowed-methods=*
spring.mvc.cors.mappings.[/**].allowed-headers=*
spring.mvc.cors.mappings.[/**].allow-credentials=false
spring.mvc.cors.mappings.[/**].max-age=3600
